### ISSUE TITLE
is necessary to update our code after latest changes in the client part?

### ISSUE THREAD

**Issue by nima-mrd** [SharifAIChallenge/AIC18-Client-Java#12]

**Comment by ali-behjati** [comment]
Yes! We'll advice you to do this asap :D Since we compile your uploaded
code and we don't change it.

**Comment by nima-mrd** [comment]
@ali-bahjati and why did you make the AI in the main thread to run?

**Comment by ali-behjati** [comment]
Because if your turn exceeds time limit your next turn will start and these
two turns running at the same time may cause undefined behavior and race
conditions.

**Comment by nima-mrd** [comment]
@ali-bahjati ok thanks! see you next week ;)
