### ISSUE TITLE
Error in code compile for friendly match

### ISSUE THREAD

**Issue by mohammerat** [SharifAIChallenge/AIC18-Client-Java#4]
بازی به صورت کاملا صحیح و سالم روی سیستم من اجرا میشه و میتونم از طریق نمایشگر هم بازی رو دنبال کنم ولی وقتی فولدر کلاینت رو فشرده میکنم و ارسال میکنم سیستم خطا میده که باید یه کد قابل کامپایل ارسال کنم.اشکال از کد است یا اشکالی در سایت است؟(کلاینت جاوا رو استفاده می کنم)

**Comment by parsamorsal** [comment]
باتشکر از اطلاع رسانی شما.
خیر مشکل از کلاینت نیست. مشکل شما به تیم مربوطه اعلام شده و فورا به آن رسیدگی خواهد شد.

**Comment by nima-mrd** [comment]
@mohammadlom کل فولدر src رو  باید زیپ کنید

**Comment by ali-behjati** [comment]
Just to follow up, does the problem still exists?
