### ISSUE TITLE
Action limitation in a Turn

### ISSUE THREAD

**Issue by nima-mrd** [SharifAIChallenge/AIC18-Client-Java#5]
how many actions **(from all 8 actions (5 defences, 3 attacks))** we can do in a **single** turn?

the default sample code (AI.java) shows we can do at most 1 move (action) in a single turn and makes sense, but I also test the other side and it's possible to do multiple actions in a single turn!

please respond as fast as possible, thanks!

**Comment by parsamorsal** [comment]
There is no limit for number of actions to do in a single turn. 
Sorry if the sample code was misleading.
