### ISSUE TITLE
Problem with game.createStorm(int, int);

### ISSUE THREAD

**Issue by parham-k** [SharifAIChallenge/AIC18-Client-Java#6]
Java Client v2.0.1:
Parameters for the method game.createStorm(int x, int y) are named as x and y but the method functions as game.createStorm(int y, int x); The parameters are misnamed.

**Comment by parsamorsal** [comment]
No, game.createStorm(int x, int y) functions correctly. it creates an storm at cells[y][x], which is the xth column in the yth row of the map grid.
I checked twice for both createStorm & plantBean and they both act accordingly.

**Comment by mahdisn76** [comment]
Please run this code and see the result
        game.createStorm(0,10);
        game.plantBean(1,10);
        game.createArcherTower(1,2,10);
![image](https://user-images.githubusercontent.com/24755996/36353414-66541100-14db-11e8-9203-aeb00fae55e2.png)

storm must be created in (0,10) but it is creating in (10,0).

**Comment by mahdisn76** [comment]
I think it is monitor's problem, because I run this code in python and the result is the same. it kills the enemies but shows the storm in a different location.

**Comment by ali-behjati** [comment]
I'm not sure about the exact problem of yours; But, it seems that log
viewer coordinates are different than the server and clients. Please take a
look at this <https://github.com/SharifAIChallenge/AIC18_Graphics/issues/11>
issue.
