### ISSUE TITLE
مشکل در از آتش زدن برج ها

### ISSUE THREAD

**Issue by mohsenaahmadi** [SharifAIChallenge/AIC18-Client-Java#8]
با سلام و خسته نباشید
درصورتی که برجی را آتش بزنیم، این برج برای خودمان روی مپ حذف می شود ولی خانه ی آن هنوز به عنوان خانه ی قابل ساخت مد نظر گرفته می شود و تابع
isTowerConstructanle() 
مقدار TRUE باز می گرداند.
در حالت مهاجم هم اگر باشیم بعد از آتش زدن در تابع  getVisbileEnemyTower() هنوز آن خانه موجود است.
لطفاً این باگ را رفع کنید . تشکر

**Comment by kiarash96** [comment]
<div dir="rtl">سلام. لطفا ورژن جدید رو دانلود کنید. احتمالا مشکل شما باید رفع شده باشه</div>
